[[libsvm]]
arch = "aarch64"
git-tree-sha1 = "4414f114c0844fa8cda199b4d071d097474674fe"
libc = "glibc"
os = "linux"

    [[libsvm.download]]
    sha256 = "c4914aab2fae35abfbd8e47b175ac814d3211428f359cbb90e3e3bdd89532b7b"
    url = "https://github.com/Leixb/libsvm_jll.jl/releases/download/libsvm-v3.31.7+0/libsvm.v3.31.7.aarch64-linux-gnu.tar.gz"
[[libsvm]]
arch = "x86_64"
git-tree-sha1 = "1d734b7bb61cabc7bd96fde0064c408b0c094509"
libc = "glibc"
os = "linux"

    [[libsvm.download]]
    sha256 = "5b1b43f56ccad830b84ac92f1f1ed3b0a14f586e0dbf543b71244e6498a68052"
    url = "https://github.com/Leixb/libsvm_jll.jl/releases/download/libsvm-v3.31.7+0/libsvm.v3.31.7.x86_64-linux-gnu.tar.gz"
